import type { Metadata } from "next";
import "./globals.scss";
import LayoutClient from "./Layout.client";
import { League_Spartan } from "next/font/google"; // Импорт шрифта из пакета Next.js

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const leagueSpartan = League_Spartan({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
